// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://wjnsfhvwrsfzpwghjjnh.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6IndqbnNmaHZ3cnNmenB3Z2hqam5oIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzI0OTI4MzcsImV4cCI6MjA4ODA2ODgzN30.X-RUfUhhHvM-NBDr5i-95jlXBWsh8U2toND3azydNEo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});